import {
    METRIC_UNITS,
    IMPERIAL_UNITS,
    START_POSITION_BACK_LEFT,
    START_POSITION_BACK_RIGHT,
    START_POSITION_FRONT_LEFT,
    START_POSITION_FRONT_RIGHT,
    SPINDLE_MODES,
    SURFACING_DWELL_DURATION,
} from 'app/constants';

import { convertToImperial } from '../../Preferences/calculate';

const [M3] = SPINDLE_MODES;

export default class EdgeJointingGenerator {
    constructor({ edgeJointing, units }) {
        this.edgeJointing = edgeJointing;
        this.units = units;
    }

    generate = () => {
        const { edgeJointing, units, getSafeZValue, toFixedValue } = this;
        const {
            boardLength,
            materialHeight,
            stepDown,
            overrun,
            feedrate,
            spindleRPM,
            startPosition,
            spindle = M3,
            shouldDwell,
            dwellDuration,
            mist,
            flood,
        } = edgeJointing;

        const safeZ = getSafeZValue();
        const setUnits = {
            [METRIC_UNITS]: 'G21 ;mm',
            [IMPERIAL_UNITS]: 'G20 ;inches',
        }[units] ?? 'G21 ;mm';

        const effectiveDwell = dwellDuration ?? SURFACING_DWELL_DURATION;
        const dwell = shouldDwell ? [`G04 P${effectiveDwell}`] : [];
        const m7 = mist ? ['M7'] : [];
        const m8 = flood ? ['M8'] : [];
        const m9 = mist || flood ? ['M9 ;Turn off Coolant'] : [];

        // Axis direction factors based on start position.
        // yFactor: 1 = board runs in +Y from zero, -1 = board runs in -Y from zero.
        const DEFAULT_FACTORS = { yFactor: 1 };
        const axisFactors = {
            [START_POSITION_FRONT_LEFT]: { yFactor: 1 },
            [START_POSITION_FRONT_RIGHT]: { yFactor: 1 },
            [START_POSITION_BACK_LEFT]: { yFactor: -1 },
            [START_POSITION_BACK_RIGHT]: { yFactor: -1 },
        }[startPosition] ?? DEFAULT_FACTORS;

        const { yFactor } = axisFactors;

        // yStart is overrun behind zero (behind the board start).
        // yEnd is the far end of the board plus overrun.
        const yStart = toFixedValue(overrun * yFactor * -1);
        const yEnd = toFixedValue((boardLength + overrun) * yFactor);

        const passCount = Math.ceil(materialHeight / stepDown);

        const gcodeArr = [
            '(Header)',
            '(Generated by gSender from Sienci Labs)',
            setUnits,
            'G90',
            `${spindle} S${spindleRPM}`,
            ...dwell,
            'G0 X0 Y0',
            `G0 Z${safeZ}`,
            ...m7,
            ...m8,
            `G1 F${feedrate}`,
            '(Header End)',
            '',
        ];

        for (let i = 1; i <= passCount; i++) {
            const depth = toFixedValue(Math.min(i * stepDown, materialHeight));

            gcodeArr.push(
                `(*** Pass ${i} of ${passCount} - Depth: ${depth} ${units} ***)`,
                `G0 Y${yStart}`,
                `G0 Z${safeZ}`,
                `G1 Z${toFixedValue(-depth)}`,
                `G1 Y${yEnd}`,
                `G0 Z${safeZ}`,
                `(*** End of Pass ${i} ***)`,
                '',
            );
        }

        gcodeArr.push(
            '(Footer)',
            ...m9,
            'M5 ;Turn off spindle',
            'G0 X0 Y0',
            '(End of Footer)',
        );

        return gcodeArr.join('\n');
    };

    getSafeZValue = () => {
        return this.units === IMPERIAL_UNITS
            ? convertToImperial(3)
            : 3;
    };

    toFixedValue(value = 0, amount = 3) {
        return Number(value.toFixed(amount));
    }
}
